# Práctica 1.1 — Probabilidad y Estadística 

## Análisis de la evolución poblacional mundial 

### Actividad 1 — Identificación de la fuente

La fuente original es **United Nations, World Population Prospects (2024)**. 

**Cita:** 

> UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

Preguntas 

Responde brevemente: 

¿Quién produjo originalmente los datos? 
United Nations

¿Qué organización los procesa para su utilización en Our World in Data? 
Our World in Data

¿Qué representa la variable que analizarás? 
anula population growth

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "C:/Users/osmar/Documents/5/bigdata/tr_1/data/raw/annual-population-growth/annual-population-growth.csv"
)

print(df.head())

        Entity Code  Year  Annual change in population  \
0  Afghanistan  AFG  1951                     103163.0
1  Afghanistan  AFG  1952                     108441.0
2  Afghanistan  AFG  1953                     108919.0
3  Afghanistan  AFG  1954                     111251.0
4  Afghanistan  AFG  1955                     119027.0

   Annual population change (Projected)
0                                   NaN
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN

In [9]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [10]:
df["Entity"].nunique()

256

In [11]:
import os

ruta = "C:/Users/osmar/Documents/5/bigdata/tr_1/data/raw/annual-population-growth"

print(os.path.isdir(ruta))
print(os.listdir(ruta))

True
['annual-population-growth.csv', 'annual-population-growth.metadata.json', 'readme.md']

Preguntas 

Responde brevemente: 

¿Cuántas filas y columnas tiene el dataset? 

¿Qué tipo de datos contiene la variable Year? 

¿Existen valores faltantes? 

¿Cuántas entidades diferentes contiene el dataset?

In [12]:
df_extraccion_entity = df[["Entity","Year"]]
# [[]] para que se mantenga como un dataframe y no como una serie
# df_extraccion_entity.head(3)
# df_extraccion_entity.shape

In [13]:
df_2020 = df[df["Year"] == 2020]
df_2020.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN

In [14]:
df_2020_ext_col1 = df_2020[["Entity","Year"]]
df_2020_ext_col1.head(3)
# Rango
df_2020_ext_col2 = df[df["Year"] == 2020] [["Entity","Year"]]
df_2020_ext_col1.head(2)

          Entity  Year
69   Afghanistan  2020
219  Africa (UN)  2020

In [15]:
# Rango
df_2005_2020 = df[ (df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Entity"] ==  "Mexico" )] 
df_2005_2020.shape

(16, 5)

In [16]:
df_ext_EA = df_2005_2020[["Year","Annual change in population"]]
df_ext_EA.head(3)

       Year  Annual change in population
22254  2005                    1417373.0
22255  2006                    1442162.0
22256  2007                    1520690.0

In [17]:
df_Mexico = df[df["Entity"] == "Mexico"]

# Trabajar con los datos

In [18]:
df_ext_EA.mean(numeric_only=True)

Year                              2012.500
Annual change in population    1400307.625
dtype: float64

# Trabajo en clases

# Actividad 3 — Estadística descriptiva

In [19]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].mean()

np.float64(135984.87179487178)

In [20]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].median()

np.float64(125190.0)

In [21]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].std()

np.float64(309877.7066206653)

In [22]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].var()

np.float64(96024193060.48312)

In [23]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].min()

np.float64(-403425.0)

In [24]:
df_G_1983_2021 = df[(df["Year"] >= 1983) & (df["Year"] <= 2021) & (df["Entity"] == "Germany")]
df_G_1983_2021["Annual change in population"].max()

np.float64(701468.0)

¿Cuál es el valor de la media? 

¿Cuál es el valor de la mediana? 

¿Cuál es el valor de la desviación estándar? 

¿Qué entidad presenta el valor mínimo y cuál el máximo?

In [25]:
columna = df["Annual change in population"]

print("Media:", columna.mean())
print("Mediana:", columna.median())
print("Desviación estándar:", columna.std())

indice_min = columna.idxmin()
indice_max = columna.idxmax()

print("Mínimo:", df.loc[indice_min, ["Entity", "Annual change in population"]])
print("Máximo:", df.loc[indice_max, ["Entity", "Annual change in population"]])

Media: 2063019.2590967466
Mediana: 46898.0
Desviación estándar: 9440859.477238411
Mínimo: Entity                           Ukraine
Annual change in population   -3315935.0
Name: 35772, dtype: object
Máximo: Entity                              World
Annual change in population    93371370.0
Name: 37839, dtype: object

In [26]:
#df_minimo = df[["Entity", "Annual change in population"]]
#df_minimo.min(numeric_only=True)

indice = df["Annual change in population"].idxmin()

print(df.loc[indice, ["Entity", "Annual change in population"]])

Entity                           Ukraine
Annual change in population   -3315935.0
Name: 35772, dtype: object

In [27]:
#df_maximo = df[["Entity", "Annual change in population"]]
#df_maximo.max(numeric_only=True)

indice = df[(df["Entity"] != "World") & (df["Entity"] != "Less developed regions" )]["Annual change in population"].idxmax()
print(df.loc[indice, ["Entity", "Annual change in population"]])

Entity                         Less developed regions, excluding China
Annual change in population                                 76359376.0
Name: 19112, dtype: object

# Actividad 4 — Comprobación del entorno

In [28]:
import sys 

 

print("Python:", sys.version) 

print("Pandas:", pd.__version__) 

print("NumPy:", np.__version__)

Python: 3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.3
NumPy: 2.4.6

In [29]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [30]:
df.loc[:,["Entity","Year","Annual change in population" ]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [31]:
df.iloc[:, [0, 1, 2]]

            Entity Code  Year
0      Afghanistan  AFG  1951
1      Afghanistan  AFG  1952
2      Afghanistan  AFG  1953
3      Afghanistan  AFG  1954
4      Afghanistan  AFG  1955
...            ...  ...   ...
38395     Zimbabwe  ZWE  2096
38396     Zimbabwe  ZWE  2097
38397     Zimbabwe  ZWE  2098
38398     Zimbabwe  ZWE  2099
38399     Zimbabwe  ZWE  2100

[38400 rows x 3 columns]

In [32]:
df.loc[10000:,["Entity","Year","Annual change in population" ]]

                  Entity  Year  Annual change in population
10000  Equatorial Guinea  2051                          NaN
10001  Equatorial Guinea  2052                          NaN
10002  Equatorial Guinea  2053                          NaN
10003  Equatorial Guinea  2054                          NaN
10004  Equatorial Guinea  2055                          NaN
...                  ...   ...                          ...
38395           Zimbabwe  2096                          NaN
38396           Zimbabwe  2097                          NaN
38397           Zimbabwe  2098                          NaN
38398           Zimbabwe  2099                          NaN
38399           Zimbabwe  2100                          NaN

[28400 rows x 3 columns]

In [33]:
df.iloc[10000:, [0, 1, 2]]

                  Entity Code  Year
10000  Equatorial Guinea  GNQ  2051
10001  Equatorial Guinea  GNQ  2052
10002  Equatorial Guinea  GNQ  2053
10003  Equatorial Guinea  GNQ  2054
10004  Equatorial Guinea  GNQ  2055
...                  ...  ...   ...
38395           Zimbabwe  ZWE  2096
38396           Zimbabwe  ZWE  2097
38397           Zimbabwe  ZWE  2098
38398           Zimbabwe  ZWE  2099
38399           Zimbabwe  ZWE  2100

[28400 rows x 3 columns]

In [40]:
df.loc[(df["Entity"] == "Mexico") & (df["Year"] == 2020)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [45]:
df.iloc[[0, 1, 2, 3, 4, 5], [0, 1, 2]]

        Entity Code  Year
0  Afghanistan  AFG  1951
1  Afghanistan  AFG  1952
2  Afghanistan  AFG  1953
3  Afghanistan  AFG  1954
4  Afghanistan  AFG  1955
5  Afghanistan  AFG  1956

In [47]:
df.iloc[:,[0, 2, 3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [48]:
df.iloc[[0, 1, 2, 3, 4], [0, 2, 3]]

        Entity  Year  Annual change in population
0  Afghanistan  1951                     103163.0
1  Afghanistan  1952                     108441.0
2  Afghanistan  1953                     108919.0
3  Afghanistan  1954                     111251.0
4  Afghanistan  1955                     119027.0